language: r
cache: packages
warnings_are_errors: false

sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"
  
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
 