language: r
cache: packages
warnings_are_errors: false

sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
 
 deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master